
2013-07-14 03:31:57+0000 [scrapy] INFO: Scrapy 0.16.4 started (bot: mfw)
2013-07-14 03:31:58+0000 [scrapy] DEBUG: Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, SpiderState
2013-07-14 03:31:58+0000 [scrapy] DEBUG: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, RedirectMiddleware, CookiesMiddleware, ProxyMiddleware, HttpCompressionMiddleware, ChunkedTransferMiddleware, DownloaderStats
2013-07-14 03:31:58+0000 [scrapy] DEBUG: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2013-07-14 03:31:58+0000 [scrapy] DEBUG: Enabled item pipelines: MfwPipeline
2013-07-14 03:31:58+0000 [mfw-lost] INFO: Spider opened
2013-07-14 03:31:58+0000 [mfw-lost] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2013-07-14 03:31:58+0000 [scrapy] DEBUG: Telnet console listening on 0.0.0.0:6024
2013-07-14 03:31:58+0000 [scrapy] DEBUG: Web service listening on 0.0.0.0:6081
2013-07-14 03:31:59+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=663235&start=100&ownerid=3945295> (referer: None)
2013-07-14 03:31:59+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:31:59+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 243-248: ordinal not in range(128)
	
2013-07-14 03:32:17+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1800&ownerid=482339> (referer: None)
2013-07-14 03:32:17+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:32:17+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-248: ordinal not in range(128)
	
2013-07-14 03:32:19+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1900&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=1800&ownerid=482339)
2013-07-14 03:32:19+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:32:19+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-248: ordinal not in range(128)
	
2013-07-14 03:32:20+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=2000&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=1900&ownerid=482339)
2013-07-14 03:32:20+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:32:20+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-248: ordinal not in range(128)
	
2013-07-14 03:32:20+0000 [mfw-lost] INFO: Closing spider (finished)
2013-07-14 03:32:20+0000 [mfw-lost] INFO: Dumping Scrapy stats:
	{'downloader/request_bytes': 1924,
	 'downloader/request_count': 4,
	 'downloader/request_method_count/GET': 4,
	 'downloader/response_bytes': 150025,
	 'downloader/response_count': 4,
	 'downloader/response_status_count/200': 4,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2013, 7, 14, 3, 32, 20, 486845),
	 'log_count/DEBUG': 10,
	 'log_count/ERROR': 8,
	 'log_count/INFO': 4,
	 'request_depth_max': 2,
	 'response_received_count': 4,
	 'scheduler/dequeued': 4,
	 'scheduler/dequeued/memory': 4,
	 'scheduler/enqueued': 4,
	 'scheduler/enqueued/memory': 4,
	 'start_time': datetime.datetime(2013, 7, 14, 3, 31, 58, 238142)}
2013-07-14 03:32:20+0000 [mfw-lost] INFO: Spider closed (finished)
