
2013-07-14 03:26:23+0000 [scrapy] INFO: Scrapy 0.16.4 started (bot: mfw)
2013-07-14 03:26:23+0000 [scrapy] DEBUG: Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, SpiderState
2013-07-14 03:26:24+0000 [scrapy] DEBUG: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, RedirectMiddleware, CookiesMiddleware, ProxyMiddleware, HttpCompressionMiddleware, ChunkedTransferMiddleware, DownloaderStats
2013-07-14 03:26:24+0000 [scrapy] DEBUG: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2013-07-14 03:26:24+0000 [scrapy] DEBUG: Enabled item pipelines: MfwPipeline
2013-07-14 03:26:24+0000 [mfw-lost] INFO: Spider opened
2013-07-14 03:26:24+0000 [mfw-lost] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2013-07-14 03:26:24+0000 [scrapy] DEBUG: Telnet console listening on 0.0.0.0:6024
2013-07-14 03:26:24+0000 [scrapy] DEBUG: Web service listening on 0.0.0.0:6081
2013-07-14 03:26:24+0000 [mfw-lost] ERROR: Error downloading <GET http://www.mafengwo.cn/group/info.php?iid=663235&start=100&ownerid=3945295>: list index out of range
2013-07-14 03:26:24+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=1148016&start=100&ownerid=5132205> (referer: None)
2013-07-14 03:26:25+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:25+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u3010' in position 238: ordinal not in range(128)
	
2013-07-14 03:26:25+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=880001&start=400&ownerid=127629> (referer: None)
2013-07-14 03:26:25+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=640338&start=100&ownerid=3945295> (referer: None)
2013-07-14 03:26:25+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:25+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 234-238: ordinal not in range(128)
	
2013-07-14 03:26:25+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:25+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-243: ordinal not in range(128)
	
2013-07-14 03:26:25+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=700&ownerid=482339> (referer: None)
2013-07-14 03:26:25+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:25+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 234-246: ordinal not in range(128)
	
2013-07-14 03:26:25+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=919732&start=700&ownerid=5045907> (referer: None)
2013-07-14 03:26:25+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:25+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-243: ordinal not in range(128)
	
2013-07-14 03:26:25+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=838094&start=400&ownerid=359664> (referer: None)
2013-07-14 03:26:25+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:25+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 234-235: ordinal not in range(128)
	
2013-07-14 03:26:26+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=800&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=700&ownerid=482339)
2013-07-14 03:26:26+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:26+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 234-246: ordinal not in range(128)
	
2013-07-14 03:26:26+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=838094&start=500&ownerid=359664> (referer: http://www.mafengwo.cn/group/info.php?iid=838094&start=400&ownerid=359664)
2013-07-14 03:26:26+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:26+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 234-235: ordinal not in range(128)
	
2013-07-14 03:26:26+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=1148016&start=200&ownerid=5132205> (referer: http://www.mafengwo.cn/group/info.php?iid=1148016&start=100&ownerid=5132205)
2013-07-14 03:26:26+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:26+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u3010' in position 238: ordinal not in range(128)
	
2013-07-14 03:26:27+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=900&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=800&ownerid=482339)
2013-07-14 03:26:28+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:28+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 234-246: ordinal not in range(128)
	
2013-07-14 03:26:28+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=838094&start=600&ownerid=359664> (referer: http://www.mafengwo.cn/group/info.php?iid=838094&start=500&ownerid=359664)
2013-07-14 03:26:28+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:28+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 234-235: ordinal not in range(128)
	
2013-07-14 03:26:29+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1000&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=900&ownerid=482339)
2013-07-14 03:26:29+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:29+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-248: ordinal not in range(128)
	
2013-07-14 03:26:29+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=838094&start=700&ownerid=359664> (referer: http://www.mafengwo.cn/group/info.php?iid=838094&start=600&ownerid=359664)
2013-07-14 03:26:29+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:29+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 234-235: ordinal not in range(128)
	
2013-07-14 03:26:30+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=919732&start=800&ownerid=5045907> (referer: http://www.mafengwo.cn/group/info.php?iid=919732&start=700&ownerid=5045907)
2013-07-14 03:26:30+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:30+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-243: ordinal not in range(128)
	
2013-07-14 03:26:37+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1100&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=1000&ownerid=482339)
2013-07-14 03:26:37+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:37+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-248: ordinal not in range(128)
	
2013-07-14 03:26:39+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1200&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=1100&ownerid=482339)
2013-07-14 03:26:39+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:39+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-248: ordinal not in range(128)
	
2013-07-14 03:26:39+0000 [mfw-lost] DEBUG: Retrying <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1300&ownerid=482339> (failed 1 times): Connection to the other side was lost in a non-clean fashion.
2013-07-14 03:26:44+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1300&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=1200&ownerid=482339)
2013-07-14 03:26:44+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:44+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-248: ordinal not in range(128)
	
2013-07-14 03:26:48+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1400&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=1300&ownerid=482339)
2013-07-14 03:26:48+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:48+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-248: ordinal not in range(128)
	
2013-07-14 03:26:49+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1500&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=1400&ownerid=482339)
2013-07-14 03:26:49+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:49+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-248: ordinal not in range(128)
	
2013-07-14 03:26:50+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1600&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=1500&ownerid=482339)
2013-07-14 03:26:50+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:50+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-248: ordinal not in range(128)
	
2013-07-14 03:26:54+0000 [mfw-lost] DEBUG: Retrying <GET http://www.mafengwo.cn/group/info.php?iid=1016671&start=100&ownerid=690315> (failed 1 times): User timeout caused connection failure.
2013-07-14 03:26:55+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=1016671&start=100&ownerid=690315> (referer: None)
2013-07-14 03:26:55+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:55+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-257: ordinal not in range(128)
	
2013-07-14 03:26:56+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1700&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=1600&ownerid=482339)
2013-07-14 03:26:56+0000 [-] ERROR: Unhandled error in Deferred:
2013-07-14 03:26:56+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 174, in _process_spidermw_output
	    dfd.addBoth(self._itemproc_finished, output, response, spider)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 327, in addBoth
	    callbackKeywords=kw, errbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/site-packages/scrapy/core/scraper.py", line 211, in _itemproc_finished
	    log.msg(level=log.DEBUG, spider=spider, **logkws)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 127, in msg
	    log.msg(**kw)
	  File "/usr/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 210, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 51, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/usr/lib/python2.7/site-packages/scrapy/log.py", line 47, in _emit
	    log.FileLogObserver.emit(self, ev)
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 410, in emit
	    util.untilConcludes(self.write, timeStr + " " + msgStr)
	  File "/usr/lib/python2.7/site-packages/twisted/python/util.py", line 833, in untilConcludes
	    return f(*a, **kw)
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 236-248: ordinal not in range(128)
	
2013-07-14 03:27:24+0000 [mfw-lost] INFO: Crawled 22 pages (at 22 pages/min), scraped 0 items (at 0 items/min)
2013-07-14 03:27:26+0000 [mfw-lost] DEBUG: Retrying <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1800&ownerid=482339> (failed 1 times): User timeout caused connection failure.
2013-07-14 03:27:27+0000 [mfw-lost] DEBUG: Crawled (200) <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1800&ownerid=482339> (referer: http://www.mafengwo.cn/group/info.php?iid=601420&start=1700&ownerid=482339)
2013-07-14 03:27:27+0000 [mfw-lost] ERROR: Spider error processing <GET http://www.mafengwo.cn/group/info.php?iid=601420&start=1800&ownerid=482339>
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/task.py", line 607, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/lib/python2.7/site-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield it.next()
	  File "/usr/lib/python2.7/site-packages/scrapy/contrib/spidermiddleware/offsite.py", line 28, in process_spider_output
	    for x in result:
	  File "/usr/lib/python2.7/site-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/lib/python2.7/site-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/lib/python2.7/site-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/home/eric/workspace/python/mfw/mfw/spiders/mfw_lost.py", line 81, in parse
	    item = self.parse_item(response, item)
	  File "/home/eric/workspace/python/mfw/mfw/spiders/mfw_lost.py", line 96, in parse_item
	    item['title'] = post.select("div[@class='post_title']/h1/text()").extract()[0]
	exceptions.IndexError: list index out of range
	
2013-07-14 03:27:27+0000 [mfw-lost] INFO: Closing spider (finished)
2013-07-14 03:27:27+0000 [mfw-lost] INFO: Dumping Scrapy stats:
	{'downloader/exception_count': 4,
	 'downloader/exception_type_count/exceptions.IndexError': 1,
	 'downloader/exception_type_count/twisted.internet.error.ConnectionLost': 1,
	 'downloader/exception_type_count/twisted.internet.error.TimeoutError': 2,
	 'downloader/request_bytes': 14918,
	 'downloader/request_count': 26,
	 'downloader/request_method_count/GET': 26,
	 'downloader/response_bytes': 2427467,
	 'downloader/response_count': 23,
	 'downloader/response_status_count/200': 23,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2013, 7, 14, 3, 27, 27, 359378),
	 'log_count/DEBUG': 32,
	 'log_count/ERROR': 46,
	 'log_count/INFO': 5,
	 'request_depth_max': 11,
	 'response_received_count': 23,
	 'scheduler/dequeued': 27,
	 'scheduler/dequeued/memory': 27,
	 'scheduler/enqueued': 27,
	 'scheduler/enqueued/memory': 27,
	 'spider_exceptions/IndexError': 1,
	 'start_time': datetime.datetime(2013, 7, 14, 3, 26, 24, 154777)}
2013-07-14 03:27:27+0000 [mfw-lost] INFO: Spider closed (finished)
